#ifndef VEXUF_H
#define VEXUF_H

typedef enum {
  UF_OK,
  UF_DISABLED,
  UF_TRIGGERED,
  UF_NOT_TRIGGERED,
  UF_NOT_CONFIGURED,
  UF_OVERWRITTEN,
  UF_CARD_EJECTED,
  UF_CARD_FULL,
  UF_ERROR,
  UF_HARD_ERROR
} UF_STATUS;

#endif  // VEXUF_H